# Generated by Django 2.0 on 2019-06-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='gender',
        ),
    ]
