# Generated by Django 2.0 on 2019-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
