# Generated by Django 2.2.2 on 2019-06-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Status',
        ),
    ]
