# Generated by Django 2.2.2 on 2019-06-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Qualified',
        ),
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.CharField(default='fff', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='board',
            field=models.CharField(default='ffff', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='city',
            field=models.CharField(default='fffff', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(default='fffffff', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='qualified',
            field=models.CharField(default='gggg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='state',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='zip1',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
