# Generated by Django 2.2.2 on 2019-06-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='password',
        ),
        migrations.RemoveField(
            model_name='details',
            name='username',
        ),
    ]
