# Generated by Django 2.2.2 on 2019-06-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190619_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.details'),
        ),
    ]
